version: '3'

services:
    php:
        image: php:8.3-cli
        volumes:
            - ./:/app
        working_dir: /app

    mysql:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: database
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
